interface:
  theme: light
  window:
    center_width: 362
    height: 600
    left_width: 261
    right_width: 275
paths:
  data_dir: data
  db_path: data\db\paper_format.db
  log_dir: logs
  prompt_dir: static\prompt
  temp_dir: temp
